steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: "npm"
    args: ["install"]
  
  # Build the React app
  - name: "node:18"
    entrypoint: "npm"
    args: ["run", "build"]
  
  # Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY